### ISSUE TITLE
Trying to understand OAuth2Result / OAuth2Error

### ISSUE THREAD

**Issue by saurabhnanda** [freizl/hoauth2#105]
I'm trying to use `Network.OAuth.OAuth2.HttpClient` properly, but I'm getting stumped because of the error handling provided by `OAuth2Result` / `OAuth2Error`.

- Do the functions at https://hackage.haskell.org/package/hoauth2-1.8.9/docs/Network-OAuth-OAuth2-HttpClient.html#g:2 (i.e. `authGetJSON`, `authPostJSON`, etc) **catch any exceptions** thrown by the underlying library? - The underlying library - `Network.HTTP.Client` - throws exceptions as documented below...

  > A note on exceptions: for the most part, all actions that perform I/O should be assumed to throw an HttpException in the event of some problem, and all pure functions will be total. For example, withResponse, httpLbs, and BodyReader can all throw exceptions.

  ...however, I could not find any `try` or `catch` at https://hackage.haskell.org/package/hoauth2-1.8.9/docs/src/Network.OAuth.OAuth2.HttpClient.html. How are exceptions being caught at all (if they are being caught in the first place)?

- **If exceptions are being caught,** how exactly are they converted into `OAuth2Error err`? What guarantees that errors sent back by the remote server are going to have the structure that `OAuth2Error err` expects, namely:

  ```
  { "error": ...
  , "error_description": ....
  , "error_uri": ...
  }
  ```

  I'm using the Quickbooks API, and am getting the following responses when I make an invalid API-call, which clearly indicates that the error JSON returned by Quickbooks has a different structure that what `OAuth2Error err` is expecting:

  ```
  Left (OAuth2Error {error = Left "Decode error", errorDescription = Just "Error: Error in $: key \"error\" not present\n Original Response:\n\"{\\\"Fault\\\":{\\\"Error\\\":[{\\\"Message\\\":\\\"Error parsing query\\\",\\\"Detail\\\":\\\"QueryParserError: Encountered \\\\\\\" <IDENTIFIER> \\\\\\\"select2 \\\\\\\"\\\\\\\" at line 1, column 1.\\\\nWas expecting:\\\\n    \\\\\\\"select\\\\\\\" ...\\\\n    \\\",\\\"code\\\":\\\"4000\\\"}],\\\"type\\\":\\\"ValidationFault\\\"},\\\"time\\\":\\\"2019-09-28T23:27:18.208-07:00\\\"}\"", errorUri = Nothing})
  ```

- **If exceptions are not being caught,** _how_ does, for example, a call to `authGetJSON` result in a `Left x` value?

**Comment by freizl** [comment]
1. Error from `Network.HTTP.Client` are not being caught. This is actually good question. The type `httpLbs` doesn't explicit indicates it throws error hence I'd assume the client who use `authGetJSON` would be able to catch error as same as catching error when using `httpLbs` cause both are in `IO` monad. I didn't personally try hence correct me wrong.

2. `IO (OAuth2Result err a)` says `authGetJSON` would either returns either a valid oauth2 response with /Right/ tokens (http code 200) or /Left/ oauth2 error (none 200)

> What guarantees that errors sent back by the remote server are going to have the structure that OAuth2Error err expects

I thought this is from oauth2 spec hence did not think how we guarantees it from this library. If the provider didn't follow the spec as Quickbook does, you would have deal with the one-off.

Having said that, any suggestions are welcome! 
I dont this oauth2 binding is elegant state nor implement the spec very well and also AFAIK, many oauth2 provider didn't strictly follow spec either.

**Comment by saurabhnanda** [comment]
> ...however, I could not find any try or catch at https://hackage.haskell.org/package/hoauth2-1.8.9/docs/src/Network.OAuth.OAuth2.HttpClient.html. How are exceptions being caught at all (if they are being caught in the first place)?

> If exceptions are not being caught, how does, for example, a call to authGetJSON result in a Left x value?

> Error from Network.HTTP.Client are not being caught. This is actually good question. The type httpLbs doesn't explicit indicates it throws error hence I'd assume the client who use authGetJSON would be able to catch error as same as catching error when using httpLbs cause both are in IO monad. I didn't personally try hence correct me wrong.

Since `authGetJSON`, et. al. return an `Either err a`, the implicit assumption is that they don't throw errors related to non-20x HTTP status codes. I was under the assumption that `httpLbs` throws an exception for non-20x responses (much like Wreq), but that is not really the case. Instead, `httpLbs` throws errors only if the underlying socket throws an error, NOT if we get a non-20x HTTP response. This is the reason why I couldn't find `try` or `catch` in the code of `Network.OAuth.OAuth2.HttpClient` (I realised all this after digging deeper into both the libraries).

> If exceptions are being caught, how exactly are they converted into OAuth2Error err? What guarantees that errors sent back by the remote server are going to have the structure that `OAuth2Error err` expects

> `IO (OAuth2Result err a)` says authGetJSON would either returns either a valid oauth2 response with /Right/ tokens (http code 200) or /Left/ oauth2 error (none 200)

> I thought this is from oauth2 spec hence did not think how we guarantees it from this library. If the provider didn't follow the spec as Quickbook does, you would have deal with the one-off.

This part still remains unsolved.

Are `authGetJSON` etc, to be used only during the authorization flow of OAuth2 OR can they _also_ be used to make authenticated/authorized calls to the actual API? If the latter, then does the OAuth spec dictate that all errors sent by the actual API be in the following structure?

```
{ "error": ...
, "error_description": ....
, "error_uri": ...
}
```

**Comment by freizl** [comment]
> Are authGetJSON etc, to be used only during the authorization flow of OAuth2

Good catch actually. The answer is No hence it's bug to return `OAuthError` for the family of functions.

**Comment by freizl** [comment]
@saurabhnanda I'd simply change the response type as `FromJSON a => IO (Either ByteString a)`
Any thoughts?
https://github.com/freizl/hoauth2/commit/83ac2ad66d72f1d0f7dc60b1ae3e5bdafa175451

**Comment by freizl** [comment]
feel free to re-open if it didn't solve the problem.
