### ISSUE TITLE
refreshAccessToken doesn't use/pass client_id & client_secret 

### ISSUE THREAD

**Issue by saurabhnanda** [freizl/hoauth2#109]
The Zoho OAuth implementation requires that `client_id` and `client_secret` are passed-in as form/URL params during `refresh_token` step. However, the [current implementation](https://hackage.haskell.org/package/hoauth2-1.9.0/docs/src/Network.OAuth.OAuth2.HttpClient.html#doSimplePostRequest) in hoauth2 library seems to apply the `client_id` and `client_secret` as a basic-auth in the header.

Apparently, both are valid implementations https://www.oauth.com/oauth2-servers/access-tokens/refreshing-access-tokens/ --

> Typically the service will allow either additional request parameters client_id and client_secret, or accept the client ID and secret in the HTTP Basic auth header.

Would it be possible to introduce another function that lets the library user select which implementation to use?

**Comment by freizl** [comment]
Thanks for reporting. Yes, it does mentioned in the RFC: https://tools.ietf.org/html/rfc6749#section-2.3.1

**Comment by freizl** [comment]
@saurabhnanda 
let me know what's your thoughts on https://github.com/freizl/hoauth2/pull/110

**Comment by saurabhnanda** [comment]
I can make sense of
https://github.com/freizl/hoauth2/pull/110/files#diff-22ccb93a51988bd0000e4852b5ef2613R79
-- which seems fine. But that MR has a whole bunch of other stuff, as well.

Can we make the haddocks clearer? I was confused between `fetchAccessToken`
and `fetchAccessToken2` and had to try both to figure out which one works.
Suggestion:

- `refreshAccessToken` - OAuth2 spec allows client_id/client_secret to
either be sent in the header (as basic authentication) OR as form/url
params. The OAuth server can choose to implement only one, or both.
Unfortunately, there is no way for the OAuth client (i.e. this library) to
know which method to use. Please take a look at the documentation of the
service that you are integrating with and either use `refreshAccessToken`
or `refreshAccessToken2`
- `refreshAccessToken2` - Please read the docs of `refreshAccessToken`


Similar changes can be made in `fetchAccessToken`

**Comment by saurabhnanda** [comment]
I can make sense of
https://github.com/freizl/hoauth2/pull/110/files#diff-22ccb93a51988bd0000e4852b5ef2613R79
-- which seems fine. But that MR has a whole bunch of other stuff, as well.

Can we make the haddocks clearer? I was confused between `fetchAccessToken`
and `fetchAccessToken2` and had to try both to figure out which one works.
Suggestion:

* `refreshAccessToken` - OAuth2 spec allows client_id/client_secret to
either be sent in the header (as basic authentication) OR as form/url
params. The OAuth server can choose to implement only one, or both.
Unfortunately, there is no way for the OAuth client (i.e. this library) to
know which method to use. Please take a look at the documentation of the
service that you are integrating with and either use `refreshAccessToken`
or `refreshAccessToken2`
* `refreshAccessToken2` - Please read the docs of `refreshAccessToken`


Similar changes can be made in `fetchAccessToken`

**Comment by freizl** [comment]
You can ignore other stuff which are basically tests/sample.
Thanks your suggestions and will update the doc.

**Comment by freizl** [comment]
https://hackage.haskell.org/package/hoauth2-1.10.1

**Comment by saurabhnanda** [comment]
Thanks you for the quick fix!
