### ISSUE TITLE
Missing Eq instances?

### ISSUE THREAD

**Issue by saurabhnanda** [freizl/hoauth2#112]
Any specific reason why `Eq` instances have not been auto-derived for a lot of the types, like `AccessToken`, `RefreshToken`, `Idtoken`, `OAuth2Token`, etc?

**Comment by freizl** [comment]
I probably didn't think of a use case. Just curious why you need to derive `Eq` ?

**Comment by saurabhnanda** [comment]
Certain oauth servers change the refresh token very often (almost every
time you try refreshing an access token, you get a new refresh token back
as well). I need to compare the new refresh token with old, and update the
DB if it has changed.

**Comment by freizl** [comment]
We could
- add `Eq` instance for `RefreshToken`
- add `Eq` to all those types

I'm leaning towards option 1 for now just to be intentional. Let me know what's your thoughts.

**Comment by freizl** [comment]
hoauth2-1.10.2
