### ISSUE TITLE
Try to support PKCE as another GrantType

### ISSUE THREAD

**Issue by freizl** [freizl/hoauth2#159]
- make it work
- See the difference with type class approach

**Comment by freizl** [comment]
See this branch: https://github.com/freizl/hoauth2/tree/haisheng/pkce-grant-type-refactor
Isn't fun to write

**Comment by ulidtko** [comment]
`won't do` ?

:frowning_face:

**Comment by freizl** [comment]
@ulidtko actually already support PKCE. what you need are basically those method from `Network.OAuth2.Experiment` module

- `mkPkceAuthorizeRequest`
- `conduitPkceTokenRequest`

This issue was trying to refactor to make a bit easier to use but I didn't figure out a better way.
