### ISSUE TITLE
Replace "login.windows.net" with "login.microsoftonline.com" in the authority host list

### ISSUE THREAD

**Issue by mirko-plowtech** [freizl/hoauth2#165]
Hi! first of all, nice library! thanks for sharing.

In the other hand, I noticed that for [defaultAzureADIdp](https://github.com/freizl/hoauth2/blob/051f7515a7b9cfe21df916ee28514af3efdfb363/hoauth2-providers/src/Network/OAuth2/Provider/AzureAD.hs#L33) in `Network.OAuth2.Provider.AzureAD` module, URIs are targeted to old names. It would be nice to update those.

Ref. https://github.com/AzureAD/azure-activedirectory-library-for-python/issues/224

**Comment by freizl** [comment]
Will look into it and will be in next release. LMK if you need sooner.
