### ISSUE TITLE
RFC: Evolution of the library

### ISSUE THREAD

**Issue by ocramz** [freizl/hoauth2#185]
Hi @freizl , I really appreciate the work you put in this library, and especially the provider defaults and the example bindings.

I was a bit taken aback by the combination of language extensions needed to run the examples: even something as trivial as updating the default records , like so :

```
azureADApp :: ClientId -> IdpApplication 'AuthorizationCode AzureAD
azureADApp clid = defaultAzureADApp{ idpAppClientId = clid }
```

triggers either a warning ("This will not be supported by -XDuplicateRecordFields in future releases of GHC.") or an error, when DuplicateRecordFields is off (on GHC 9.2.7).

My concern is not with this design per se, but rather with your hints that this will become the default API of the library from version 3.0

Even as an experienced Haskeller, I am a bit wary that such a key piece of web infrastructure poses this kind of API hurdles, and I would very much welcome a discussion on "simpler" (in the sense of simple Haskell) API design alternatives.

**Comment by freizl** [comment]
Thanks your feedback @ocramz !

I think you'd worry less about `the default API of the library from version 3.0` given I didn't have any timeline for 3.0 hence I leave comments in the code like this

> -- This module will become default in future release. (TBD but likely 3.0).

The goal for putting this design in experimental mode is getting feedback!

- Do you like the design?
- Do you feel it's over-design/complicated to use type family?
- Do you have thoughts to simplify or go another direction like having different namespace per grant type and people can just call it.
```
module Network.OAuth2.AuthorizationCode
module Network.OAuth2.ResourceOwnerPassword
module Network.OAuth2.ClientCredentials
...
```

Each module would have the way to construct login url, handle callback etc.

- Any other questions/suggestions?

**Comment by freizl** [comment]
One thing I could think of is to make unique name for each IdP App. e.g. `AuthorizationCodeIdpApplication` would become

```
data instance IdpApplication 'AuthorizationCode i = AuthorizationCodeIdpApplication
  { acIdpAppName :: Text
  , acIdpAppClientId :: ClientId
  , acIdpAppClientSecret :: ClientSecret
  ...
  }
```

Another I was trying but didn't make it work is to define those data instance in its own module such that we could qualified the field when using. So you sample code would become

```
azureADApp :: ClientId -> IdpApplication 'AuthorizationCode AzureAD
azureADApp clid = defaultAzureADApp{ AuthorizationCode.idpAppClientId = clid }
```

**Comment by freizl** [comment]
Don't take this as suggestion but trick work around:
If you're override other fields (which I feel is likely), you won't get the warning on using `XDuplicateRecordFields`

```
  azureADApp
    { idpAppClientId = ""
    , idpAppClientSecret = ""
    , idpAppAuthorizeState = AuthorizeState ("test." <> randomStateValue)
    , idpAppRedirectUri = [uri|http://localhost:9988/oauth2/callback|]
    }
```

I bet this is because GHC is able to disambiguate due to those non-duplicated fields.

**Comment by freizl** [comment]
I think #191 make the experiment module simpler.
Feel free to re-open or open a new issue for further suggestions.
