### ISSUE TITLE
Move from 'cryptonite' to 'crypton'

### ISSUE THREAD

**Issue by ocramz** [freizl/hoauth2#188]
Apparently 'cryptonite' is not actively maintained, and 'crypton' is the new standard. 

A number of key networking libraries have switched to 'crypton' already : https://packdeps.haskellers.com/reverse/crypton 

It's API-compatible, so this should be just an import renaming chore.

**Comment by freizl** [comment]
https://hackage.haskell.org/package/jose-jwt-0.9.5 still depends on `cryptonite`

**Comment by ocramz** [comment]
Hi @freizl ! The latest jose-jwt depends on crypton:  https://hackage.haskell.org/package/jose-jwt-0.10.0

**Comment by freizl** [comment]
publish `hoauth2-1.13.0`
let me know if any issues.
