### ISSUE TITLE
Facebook: Error validating verification code. 

### ISSUE THREAD

**Issue by pmlodawski** [freizl/hoauth2#19]
I'm not sure it is a bug in your code or rather in my facebook app configuration. When I run it I get an error:

    ➜  hoauth2 git:(master) ✗ ./example/Facebook/test 
    "https://www.facebook.com/dialog/oauth?client_id=317076475103268&response_type=code&redirect_uri=http%3A%2F%2Flocalhost&scope=user_about_me%2Cemail"
    visit the url and paste code here: 
    __REMOVED__
    test: StatusCodeException (Status {statusCode = 400, statusMessage = "Bad Request"}) [("Access-Control-Allow-Origin","*"),("Cache-Control","no-store"),("Content-Type","application/json"),("Expires","Sat, 01 Jan 2000 00:00:00 GMT"),("Pragma","no-cache"),("WWW-Authenticate","OAuth \"Facebook Platform\" \"invalid_code\" \"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request\""),("X-FB-Rev","924754"),("X-FB-Debug","__REMOVED__"),("Date","Tue, 03 Sep 2013 08:37:37 GMT"),("Connection","keep-alive"),("Content-Length","190"),("X-Response-Body-Start","{\"error\":{\"message\":\"Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request\",\"type\":\"OAuthException\",\"code\":100}}")] (CJ {expose = []})
I have listed http://localhost in "Valid OAuth redirect URIs" in facebook app configuration

**Comment by freizl** [comment]
closed as no further update and not able to replicate it.
re-open if you met it again.
