### ISSUE TITLE
Interface stability - breaking changes between 2.6 and 2.8

### ISSUE THREAD

**Issue by ocramz** [freizl/hoauth2#193]
Some breaking changes between 2.6.0 and 2.8.0 related to the error types being moved and renamed : 

`Module ‘Network.OAuth.OAuth2’ does not export ‘OAuth2Error’` (this import works for 2.6 but doesn't for 2.8)

**Comment by freizl** [comment]
https://github.com/freizl/hoauth2/pull/168

**Comment by ocramz** [comment]
Good to know that the change was documented and where to look for this! Just I was expecting that breaking changes would only occur between major versions, since this package is already past v2.0

**Comment by freizl** [comment]
Base on [PVP](https://pvp.haskell.org/), I think break changes can be include as long as `A.B` is greater.
