### ISSUE TITLE
RFC: hoauth2-providers: AzureAD requires tenant-specific endpoints

### ISSUE THREAD

**Issue by ocramz** [freizl/hoauth2#195]
Verified with hoauth-2.6.0

If an AAD app is single-tenant, and you use the `defaultAzureADIdp`, you get the following error:

```
Sorry, but we’re having trouble signing you in.

AADSTS50194: Application 'appId'(appname) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.
```

Perhaps `hoauth2` could provide a smart constructor for the `IdP` to take care of this.

**Comment by freizl** [comment]
Are you working on your own AD tenant instead of global one?
Would you give example of how does the tenant-specific endpoint look like?

We'd likely to make helper like [this](https://github.com/freizl/hoauth2/blob/5a4524c52b2c17aa09d9d8d17e789836ba589726/hoauth2-providers/src/Network/OAuth2/Provider/Auth0.hs#L66)

**Comment by ocramz** [comment]
The tenant-specific endpoint replaces `common` with the tenant name (or tenant ID):


e.g. `https://login.microsoftonline.com/contoso.onmicrosoft.com`

https://learn.microsoft.com/en-us/answers/questions/960066/aad-returned-an-error-response-case-usage-of-the-c

**Comment by freizl** [comment]
@ocramz I dont have AD tenant to test. Would you mind to take look at this method to see if works for you?
https://github.com/freizl/hoauth2/pull/196

**Comment by freizl** [comment]
Fixed in https://github.com/freizl/hoauth2/pull/196
