### ISSUE TITLE
Strengthen `base` lower bound to `>= 4.14`.

### ISSUE THREAD

**Issue by andreasabel** [freizl/hoauth2#244]
https://github.com/freizl/hoauth2/blob/3715b9e3939676cc7e35c669726aff23dbe50e39/hoauth2/hoauth2.cabal#L68
More accurate would be `base >= 4.14 && < 5` since you require GHC 8.10 or higher (because of `ImportQualifiedPost`).

**Comment by freizl** [comment]
Fixes in https://github.com/freizl/hoauth2/pull/241
