### ISSUE TITLE
hoauth2-providers 0.7.1 build fail

### ISSUE THREAD

**Issue by tfc** [freizl/hoauth2#248]
On version 0.7.1 of `hoauth2-providers` i am currently getting this error:

```
src/Network/OAuth2/Provider/Google.hs:108:34: error: [GHC-83865]
    • Couldn't match expected type ‘cryptonite-0.30:Crypto.PubKey.RSA.Types.PrivateKey’
                  with actual type ‘PrivateKey’
      NB: ‘cryptonite-0.30:Crypto.PubKey.RSA.Types.PrivateKey’
            is defined in ‘Crypto.PubKey.RSA.Types’
                in package ‘cryptonite-0.30’
          ‘PrivateKey’
            is defined in ‘Crypto.PubKey.RSA.Types’ in package ‘crypton-0.34’
    • In the second argument of ‘rsaEncode’, namely ‘privateKey’
      In the second argument of ‘(<$>)’, namely
        ‘rsaEncode RS256 privateKey payload’
      In a stmt of a 'do' block:
        first show <$> rsaEncode RS256 privateKey payload
    |
108 |   first show <$> rsaEncode RS256 privateKey payload
    | 
```

I'm using Nix, not Stack.
But as far as I can see, the project uses Stackage LTS 21.1 which has the same package versions according to the Stackage Package search.

These are the other package versions:

```
Configured component graph:
    component hoauth2-providers-0.7.1-2LHVTjfdYMmJ5sIKMxnHVp
        include HsOpenSSL-0.11.7.6-FNfAKurO59x6j4NyhdMVdz
        include aeson-2.2.1.0-7A2Tv95lbefArgaBl5w1J7
        include base-4.19.0.0-inplace
        include bytestring-0.12.0.2-inplace
        include containers-0.6.8-inplace
        include crypton-0.34-6qMoOQNrVAFA4Ousp5cWzp
        include hoauth2-2.13.1-1Ot1KIGUpde6lNDrfydu8l
        include http-conduit-2.3.8.3-HmEeL857GMa5mRtZm53a6R
        include http-types-0.12.4-7bj1JQvKNRj3AnMjzjUPgh
        include jose-jwt-0.9.6-IK8KdjTG4B0GFiLaYkviTr
        include mtl-2.3.1-inplace
        include text-2.1-inplace
        include time-1.12.2-inplace
        include transformers-0.6.1.0-inplace
        include uri-bytestring-0.3.3.1-3ngoL0IBORhGCqchnY6w9S
        include uri-bytestring-aeson-0.1.0.8-C8EO8AQLUEtFem4etTBYU2
```

Is something else too old/new? I've seen the ticket about moving from cryptonite to crypton, so it feels like some dependency didn't do the same update as this project.

**Comment by tfc** [comment]
PEBCAK - sorry for the noise :'-D

**Comment by alleksandrgall** [comment]
@tfc Sorry for necroposting, can you provide what helped you in the end? Having the exact issue, can't seem to figure it out.

**Comment by freizl** [comment]
I shall use package `crypton` but somehow it points to `cryptonite` (my guess) ?

**Comment by tfc** [comment]
> [@tfc](https://github.com/tfc) Sorry for necroposting, can you provide what helped you in the end? Having the exact issue, can't seem to figure it out.

I should have documented what helped here, but i didn't - my fault.

Not completely sure what I did, but i think using [Horizon Haskell](https://horizon-haskell.net/) and adding the package there helped because this way I got the latest version and that works.

**Comment by alleksandrgall** [comment]
Thanks for answering.
In the end it took an override of `jose-jwt` to the latest version from nixpkgs-unstable and everything works.

```nix
haskellProjects.default = {
  settings = {
    jose-jwt = {super, ...}: {custom = _: super.jose-jwt_0_10_0;};
  };
};
```
