### ISSUE TITLE
Remove monad-control

### ISSUE THREAD

**Issue by tensor5** [freizl/hoauth2#35]
It doesn't need `monad-control` in https://github.com/freizl/hoauth2/blob/master/hoauth2.cabal, it's not imported anywhere. You should also check the other dependencies.

**Comment by freizl** [comment]
Thank you and let me get ride of it.
How did you find such un-usage? by any tools or other?

**Comment by tensor5** [comment]
I manage an Arch Linux [repository](https://github.com/tensor5/haskell-happstack) of Haskell packages, which includes `hoauth2`. When `monad-control-1.0` came out I had to write a patch for `hoauth2` because it would not compile, and that's when I realized that it didn't actually depend on it!
I didn't check any other dependency beside `monad-control`, though.

**Comment by freizl** [comment]
Gotcha. Thanks and publish a new package.
