### ISSUE TITLE
Authentication error with Google

### ISSUE THREAD

**Issue by gip** [freizl/hoauth2#38]
My application and the test included in the repo now returns the following error when authenticating with Google: "OAuth 2 parameters can only have a single value: client_id"

I've just tried the test included in this repo and it seems to fail as well. 

It is likely that hoauth2 isn't fully compliant with the standard. This issue pops up now because Google changed something recently -- see http://stackoverflow.com/questions/29694840/googles-openid-connect-says-oauth-2-parameters-can-only-have-a-single-value-c

**Comment by freizl** [comment]
hmm, interesting finding. i'll take a look.

**Comment by freizl** [comment]
@gip if the problem still persist ?
The [example](https://github.com/freizl/hoauth2/blob/master/example/Google/test.hs) run successfully. Otherwise could you provide code sample?

**Comment by alpacaaa** [comment]
I think I'm seeing the same with Dropbox. The error returned by the api says you can't send the `Authorization` header together with the `client_secret` arg. This is my configuration for reference:

```
config = OAuth2 {
  oauthClientId = "xxx",
  oauthClientSecret = "xxx",
  oauthOAuthorizeEndpoint = "https://api.dropboxapi.com/oauth2/authorize",
  oauthAccessTokenEndpoint = "https://api.dropboxapi.com/oauth2/token",
  oauthCallback = Nothing
}
```

Thanks

**Comment by gip** [comment]
Yes I can confirm that the problem still exists. I'm currently using a
modified local version to make that work. Didn't do a PR yet as I couldn't
figure out which of the header or the argument should be sent. Thoughts?

**Comment by alpacaaa** [comment]
@gip Not sure honestly, an oauth2 server should support both. I took a look at a couple of other libraries (in other languages) and there doesn't seem to be consensus on which one has priority. A PR would be really nice, thanks in advance if you'll take the time to submit it.

**Comment by freizl** [comment]
thanks your reporting and @gip could you share your local modification?

**Comment by freizl** [comment]
@gip @alpacaaa 
would you mind taking an review https://github.com/freizl/hoauth2/pull/54

**Comment by freizl** [comment]
@gip @alpacaaa
close this thread now and please reopen if it still persist.
thank you!

**Comment by alpacaaa** [comment]
Finally had the chance to test this, it is fixed, thanks! Have a great new year :cheese:

**Comment by freizl** [comment]
@alpacaaa thanks for testing and happy new year!
