### ISSUE TITLE
Security issue on exceptions

### ISSUE THREAD

**Issue by jprider63** [freizl/hoauth2#39]
Certain responses (like 401) from the OAuth provider can cause exceptions to be thrown when calling `authGetJSON`. This is problematic because Yesod displays exceptions to the end user automatically, which can contain the URL including GET variables with secret access tokens. 

As a temporary fix, I've wrapped `authGetJSON` with `catchAny` from `Control.Exception.Enclosed`. 

```
authGetJSON' manager token url = catchAny (authGetJSON manager token url) handler
    where
        handler e = return $ Left $ BSL8.pack $ show e
```

**Comment by freizl** [comment]
Thanks. That looks good.

Would be better to allow library User to handler it rather than `hoauth2` default it?
I mean like
`catchAny authGetJSON' handler`
My understanding it'll open flexibility to end user.

**Comment by jprider63** [comment]
I think the best solution would be to track down what's causing the exception and have it return something like `Left "Unauthorized"` instead.

**Comment by freizl** [comment]
I'd prefer the idea that return something like `Left "Unauthorized"` and it probably shall wrap all possible errors that declared by their API.
I'm busy those days and hopefully have time in following month.
PR is welcome.

**Comment by jprider63** [comment]
I'm not sure when I can get around to it, but I'll take a shot when I get the chance. I briefly took a look to find the code that is throwing the exception, but it wasn't immediately obvious to me. Do you have any hints to where you think it might be?

**Comment by freizl** [comment]
Thanks much!

I suspect it'll be at `handleResponse`. Otherwise I'll need to know what exact error and take a close look as well.

```
handleResponse :: Response BSL.ByteString -> OAuth2Result BSL.ByteString
handleResponse rsp =
    if HT.statusIsSuccessful (responseStatus rsp)
        then Right $ responseBody rsp
        else Left $ BSL.append "Gaining token failed: " (responseBody rsp)
```

**Comment by jprider63** [comment]
Ok thanks. I'll start there. FYI, it was a [StatusCodeException](http://hackage.haskell.org/package/http-client-0.4.11.1/docs/Network-HTTP-Client-Internal.html#v:StatusCodeException).

**Comment by freizl** [comment]
The library doesn't swallow the exception. (see `handleResponse` above)

**Comment by freizl** [comment]
Close due to inactivity.
