### ISSUE TITLE
Build with aeson 0.10 & http-types 0.9

### ISSUE THREAD

**Issue by DanBurton** [freizl/hoauth2#43]
yesod-auth-oauth2 is currently being excluded from stackage because it depends on hoauth2, which isn't compatible with the latest aeson and http-types.

See: fpco/stackage#845 and fpco/stackage#880 for context.
See also: thoughtbot/yesod-auth-oauth2#48

**Comment by freizl** [comment]
Updated and bump version to `0.5.0`. Please let me any further problems.

```
aeson             >= 0.10   && < 0.11,
http-types        >= 0.9    && < 0.10
```

**Comment by freizl** [comment]
Open again in case does not work for you.

**Comment by DanBurton** [comment]
Works for https://github.com/thoughtbot/yesod-auth-oauth2/issues/48. Works for me. Thanks!
