### ISSUE TITLE
Facebook OAuth 'missing client_id' in versions > 0.5.5

### ISSUE THREAD

**Issue by kiambogo** [freizl/hoauth2#55]
After upgrading hoauth2 to anything above 0.5.5 I receive the following error from Facebook when making a POST request to retrieve an access token: 
    
     {\"error\":{\"message\":\"Missing client_id    parameter.\",\"type\":\"OAuthException\",\"code\":101,\"fbtrace_id\":\"AKOkEeCq8LL\"}}

The code that invokes this didn't change since the upgrade, and is as follows: 

          get "/oauth/facebook" $ do
            r <- request
            code <- param "code"
            mgr <- liftIO $ newManager tlsManagerSettings
            let (url, body) = accessTokenUrl oauthConf code
            resp <- liftIO $ doJSONPostRequest mgr oauthConf url (body ++ [("state", "test")])
            case (resp :: OAuth2Result AccessToken) of
              Right token -> do
                user <- liftIO $ userinfo' mgr token

Was the `client_id` removed from being set in the query parameters in the `doJSONPostRequest`? I took a look at the source code and it doesn't look like that method or the helper methods it invokes changes.

**Comment by freizl** [comment]
Looks like facebook changed the way to obtain an access token..
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow

**Comment by freizl** [comment]
an temporary solution

```{.haskell}
    let (url, body) = accessTokenUrl facebookKey code
        url2 = appendQueryParam url (transform' [ ("client_id", Just $ oauthClientId facebookKey)
                                                , ("client_secret", Just $ oauthClientSecret facebookKey)
                                                , ("state", Just "test")
                                                ] ++ body)
    req2 <- parseUrl (BS.unpack url2)
    resp <- fmap (parseResponseJSON . handleResponse) (httpLbs req2 mgr)

```

**Comment by kiambogo** [comment]
Thanks for the response @freizl, I will try out your temporary solution.

I'm confused as to why version 0.5.5 of this library works though - if Facebook changed the way you obtain an access token I would imagine that this would break across all versions. Do you have any thoughts as to why 0.5.5 continues to work properly?

**Comment by freizl** [comment]
@kiambogo good catch. I think it's probably because of https://github.com/freizl/hoauth2/commit/88b78ab1eb7c2268679046e7db6fb8ba69b815fa#diff-93c1b88959012b8fb902e8d865fd4025

turns out vendors have none consistent oauth2 implement.
I'll have further investigation and refactor this lib properly.

Thanks for reporting!

**Comment by x1ddos** [comment]
Re: non consistent implementation. There are actually quite a few of them. It's just many of them implemented the spec at the time it wasn't finalised and, unfortunately, their implementation remained that way.

Somewhat related. Here's a list of "broken" providers, listed in a Go oauth2 package: https://github.com/golang/oauth2/blob/de0725b330ab43c1a3d6c84d961cf01183783f1e/internal/token.go#L92-L122

Also, note the following: https://github.com/golang/oauth2/blob/de0725b330ab43c1a3d6c84d961cf01183783f1e/internal/token.go#L56-L64

**Comment by freizl** [comment]
a temporary solution by adding another method `fetchAccessToken2`.
