### ISSUE TITLE
`fetchRefreshToken` fails, expecting `Text` but receiving `Object`

### ISSUE THREAD

**Issue by saylu** [freizl/hoauth2#62]
I tried to set up a working Google integration today and ran into this error when trying to refresh an access token (I could not get the examples to build and refresh properly, either):

```
Left "hoauth2.HttpClient.parseResponseString/Could not decode URL: {\n  \"access_token\" : \"lt_...EFpxs_m\",\n  \"expires_in\" : 3600,\n  \"id_token\" : \"eyJhbGc...6VO_CRWw\",\n  \"token_type\" : \"Bearer\"\n}"
```

I was puzzled, as fetching an access token works perfectly well. I found that this function [relies on `doFlexiblePostRequest`](https://hackage.haskell.org/package/hoauth2-1.2.0/docs/src/Network-OAuth-OAuth2-HttpClient.html#fetchRefreshToken), which tries first to parse the JSON and then to parse the URL. So this error is misleading. By forcing it to try the JSON, I saw this:

```
Left "hoauth2.HttpClient.parseResponseJSON/Could not decode JSON: {\n \"access_token\": \"y...cyuCn9YY6SpPd0P4GHlWpcBgg9_o8uVX2RiBHYY0As2Y8wmmHUmO\",\n \"token_type\": \"Bearer\",\n \"expires_in\": 3600\n}\n, with error: 
Error in $: expected Text, encountered Object"
```

This was confusing, until I realized the instance of `FromJSON` for `AccessToken`, the return type for this function, is just this:

```
newtype AccessToken = AccessToken { atoken :: Text } deriving (Show, FromJSON, ToJSON)
```

But what Google sends over is this:

```
{
\n \"access_token\": \"y...G\",
\n \"token_type\": \"Bearer\",
\n \"expires_in\": 3600\n}
}
```

To remedy the problem, I made a new data type that I could derive instances from just as is done with the overall `OAuth2Token`.  The code written below works successfully to refresh tokens.

```haskell
data OAuthRefreshToken = OAuthRefreshToken {
      accessToken :: AccessToken
    , tokenType   :: Maybe Text
    , expiresIn   :: Maybe Int
    } deriving (Show, Generic)

instance FromJSON OAuthRefreshToken where
    parseJSON = genericParseJSON defaultOptions { fieldLabelModifier = camelTo2 '_' }
instance ToJSON OAuthRefreshToken where
    toEncoding = genericToEncoding defaultOptions { fieldLabelModifier = camelTo2 '_' }

fetchRefreshToken ::
     Manager
  -> OAuth2
  -> RefreshToken
  -> IO (OAuth2Result OAuthRefreshToken)
fetchRefreshToken manager oa token = doJSONPostRequest manager oa uri body
    where (uri, body) = refreshAccessTokenUrl oa token
```

I don't know what you'd prefer to do as the answer to this problem so I haven't submitted a PR. Instead, I'm sharing my solution here.

Cheers!
Thomas

**Comment by freizl** [comment]
@saylu thanks for reporting the issue!
I did an fix and btw there is an example running such scenario https://github.com/freizl/hoauth2/blob/master/example/Google/test.hs#L83-L104
Please let me know if it works for you or not.

**Comment by freizl** [comment]
I'll release an new version if everything works well.

**Comment by saylu** [comment]
Whew! Looks like I went overboard there. I looked at your diff and I noticed that the only real necessary change is the return type of `fetchRefreshToken` from `AccessToken` to `OAuth2Token`.

To test this out in my code, I simply included, as the replacement for the current `fetchRefreshToken`, the following version:

```haskell
fetchRefreshToken ::
     Manager -- ^ HTTP connection manager.
  -> OAuth2 -- ^ OAuth context
  -> RefreshToken -- ^ refresh token gained after authorization
  -> IO (OAuth2Result OAuth2Token)
fetchRefreshToken manager oa token = doJSONPostRequest manager oa uri body
    where (uri, body) = refreshAccessTokenUrl oa token
```

This is identical except for the return type. And then I just have to retrieve the new access token:

```haskell
... accessToken newOAuth2Token ...
```

And it works just fine. Thanks for your time.

**Comment by freizl** [comment]
Cool. I'll release `1.3.0` shortly.

**Comment by freizl** [comment]
1.3.0 was uploaded. it's broken change that return type of those fetching function were changed being explicitly about errors.
you could check samples for reference. let me if any questions, problems. thanks!
