### ISSUE TITLE
Clarify value of `oauthCallback` field in examples

### ISSUE THREAD

**Issue by ChShersh** [freizl/hoauth2#92]
In the examples for this library I see the following value `oauthCallback` for Fitbit IDP:

```haskell
oauthCallback = Just [uri|http://localhost:9988/oauth2/callback|]
```

If I understood OAuth2 correctly then this should be URL that is called by Fitbit server in form:

```
http://localhost:9988/oauth2/callback?code=Foo&state=Bar
```

But how could it call my localhost? Does it mean that I can't test OAuth2 locally and I need some deployed globally accessible server for this, that implements `/oauth2/callback?code=Foo&state=Bar` endpoint?

**Comment by freizl** [comment]
@ChShersh you need to implement a http server locally in order to test.
check sample project at https://github.com/freizl/hoauth2/tree/master/example

it's actually not "called" by IdP but a redirect to `oauthCallback` from IdP.

**Comment by ChShersh** [comment]
@freizl Could you, please, tell some steps explaining how can I run your example to test with something like Fitbit? Probably this could also help to resolve the following issue:

* https://github.com/freizl/hoauth2/issues/86

The size of code in `example` is not that small and doesn't have documentation so it's not that simple to read it and try to do the same.

**Comment by freizl** [comment]
@ChShersh 

I assume you had a few experience at understanding what's oauth2 and how to develop a oautth2 client.

check the Makefile (https://github.com/freizl/hoauth2/blob/master/Makefile) and basically it's
- make create-keys
- check the `example/Keys.hs` to make sure it's config correctly for the IdP you're going to test. (client id, client secret, oauth Urls etc)
- make build
- make demo

then open http://localhost:9988 and you shall be able to test from there on.

**Comment by ChShersh** [comment]
@freizl Thanks! Your instructions were really helpful. It works great for me 👌
