### ISSUE TITLE
Library isn't working with Google Gmail API

### ISSUE THREAD

**Issue by gip** [freizl/hoauth2#94]
I'm trying to use `authPostBS` to send emails through Gmail API. I'm running into two issues:
1. Functions `authPostBS` adds the token to the body *and* the headers, which I believe deviates from the OAuth 2 specs.
2. When using `authPost*` family of functions, there is no way to set the content type header as far as I see.

To make my code work I had to implement something like below (see `authPostBS99`). I also had to change the `updateRequestHeaders` function to add the missing `application/json`. This is not ideal as it breaks backward compatibility. 

Is there something I'm missing here? Has this code been tested with Google API?

```haskell
-- | Conduct POST request.
authPostBS99 :: FromJSON err => Manager                -- ^ HTTP connection manager.
             -> AccessToken
             -> URI
             -> BSL.ByteString
             -> IO (OAuth2Result err BSL.ByteString) -- ^ Response as ByteString
authPostBS99 manager token url body = do
  req <- uriToRequest url
  authRequest req upReq manager
  where upBody req = req { requestBody = RequestBodyLBS body }
        upHeaders = updateRequestHeaders (Just token) . setMethod HT.POST
        upReq = upHeaders . upBody
```

**Comment by freizl** [comment]
@gip 
- yeah, `authPost*` didn't provide away for updating request header. this is something in the TODO list.
- `updateRequestHeaders` does add `application/json` accept type, doesn't it?
- I wonder if you need to post a request with JSON body? I might miss that function cause IdPs I tested before usually accept form post.

**Comment by freizl** [comment]
`authPostBS2` or `authPostBS3` only adds token to body or header respectively
Though still not ideal but hopefully it's helpful a little bit!

Feel free to re-open if any other questions.
